// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/word/search": {
            "get": {
                "description": "search word",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "word search",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.WordNode"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_active_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.WordDefinition": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "keyword": {
                    "type": "string"
                },
                "meaning": {
                    "type": "string"
                },
                "word_name": {
                    "type": "string"
                }
            }
        },
        "model.WordNode": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "left_node": {
                    "$ref": "#/definitions/model.WordNode"
                },
                "left_node_id": {
                    "type": "integer"
                },
                "parent_node": {
                    "$ref": "#/definitions/model.WordNode"
                },
                "parent_node_id": {
                    "type": "integer"
                },
                "right_node": {
                    "$ref": "#/definitions/model.WordNode"
                },
                "right_node_id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                },
                "user_id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "word_definition": {
                    "$ref": "#/definitions/model.WordDefinition"
                },
                "word_definition_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
